### ISSUE TITLE
Filter not working with Spring boot and HATEOAS

### ISSUE THREAD

**Issue by frankie-2e** [bohnman/squiggly-filter-jackson#7] opened 2017-04-26 11:40 UTC
Hi,

I wrote a simple [POC application](https://github.com/frankie-2e/squiggly-poc) using your [Spring Boot example](https://github.com/bohnman/squiggly-filter-jackson/tree/master/examples/spring-boot) as a template.

In addition to your example project, the project I wrote uses the _spring-boot-starter-hateoas_ dependancy, needed in order to generate the links in the REST response.

After starting the project and attempting to use the filter, e.g. 

`curl -s -g 'http://localhost:8080/issues?fields=issueSummary'`

the filter runs correctly:
```
[
  {
    "issueSummary": "Dragons Need Fed"
  },
  {
    "issueSummary": "More wine please!"
  },
  {
    "issueSummary": "Hello Kitty pillow missing"
  }
]
```
However, when attempting to filter a single entity, e.g.

`curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=issueSummary'`

the filter is not applied and the whole entity is passed back in json:

```
{
  "issueId": "ISSUE-1",
  "issueSummary": "Dragons Need Fed",
  "issueDetails": "I need my dragons fed pronto.",
  "reporter": {
    "firstName": "Daenerys",
    "lastName": "Targaryen"
  },
  "assignee": {
    "firstName": "Jorah",
    "lastName": "Mormont"
  },
  "actions": [
    {
      "issueId": null,
      "type": "COMMENT",
      "text": "I'm going to let Daario get this one..",
      "user": {
        "firstName": "Jorah",
        "lastName": "Mormont"
      }
    },
    {
      "issueId": null,
      "type": "CLOSE",
      "text": "All set.",
      "user": {
        "firstName": "Daario",
        "lastName": "Naharis"
      }
    }
  ],
  "properties": {
    "priority": "1",
    "email": "motherofdragons@got.com"
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/issues/ISSUE-1"
    }
  }
}
```

Am I doing something wrong or is that actually a bug in the filter? Please advise.

Regards,
Frankie

**Comment by bohnman** [comment] 2017-04-26 14:35
I was able to reproduce the issue.  I should have a workaround for you in the next 24 hours.

**Comment by bohnman** [comment] 2017-04-27 00:02
Frankie,

Here are the steps to get Squiggly to work with your project:

Upgrade your squiggly dependency to version 1.3.2

```xml
<dependency>
    <groupId>com.github.bohnman</groupId>
    <artifactId>squiggly-filter-jackson</artifactId>
    <version>1.3.2</version>
</dependency>
```

Change your Application.java to look like the following:

```java
@SpringBootApplication
public class Application {
    
    @Bean 
    public FilterRegistrationBean squigglyRequestFilter() {
        FilterRegistrationBean filter = new FilterRegistrationBean();
        filter.setFilter(new SquigglyRequestFilter());
        filter.setOrder(1);
        return filter;
    }

    public static void main(String[] args) throws Exception {
        Iterable<ObjectMapper> objectMappers = SpringApplication.run(Application.class, args)
                .getBeansOfType(ObjectMapper.class)
                .values();

        Squiggly.init(objectMappers, new RequestSquigglyContextProvider());
    }

}
```

This will now allow you to filter individual resources.  However, I encountered two additional issues that you should be made aware of:

1) Selecting properties in HATEOS link fields do not work.  For example, this does not work

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=_links.self.href'
```

This is because there is a @JsonUnwrapped annotation, which Squiggly doesn't currently support.  I have created an enhancement for this: https://github.com/bohnman/squiggly-filter-jackson/issues/8

2) You are running a newer version of Tomcat than what is in the examples.  Apparently, newer versions of Tomcat are much more strict about what characters they allow in the url.  This includes throwing an exception when braces are specified.

For example, this will not work:

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=reporter{firstName}'
```

One way to get around this is to escape the braces

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=reporter%7BfirstName%7D'
```

That is ugly.  Another way to have curl escape it

``` bash
 curl -s -G 'http://localhost:8080/issues/ISSUE-1' --data-urlencode 'fields=reporter{firstName}'
# notice the capital G
```

However, this does not work for the browser.  A third way is to use dot notation:

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=reporter.firstName'
```

This works, but now you have to repeat the path if you want to select multiple nested fields.

As of 1.3.2, you can now specify nested fields using square brackets like so:

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=reporter[firstName]'
```

Hope this helps!

**Comment by frankie-2e** [comment] 2017-04-27 08:26
Hi Ryan,

Thank you very much for the quick action and detailed response, as well as the tips about how to use _curl_ more efficiently!

Registering Squiggly against all ObjectMapper instances definitely solves the issue of filter being ignored. However, this is only the part of the problem, as the @JsonUnwrapped annotation is still not supported.

Is there any indication about when a version supporting the @JsonUnwrapped annotation might be rolling out?

Regards,
Frankie

**Comment by bohnman** [comment] 2017-04-27 13:08
I'll probably take a look this weekend.  But, don't hold me to it!  :-)

**Comment by bohnman** [comment] 2017-04-29 00:07
Frankie,

I have implemented support for @JsonUnwrapped.

1) update your dependency to version 1.3.3

2) the following filter should work

```bash
curl -s -g 'http://localhost:8080/issues/ISSUE-1?fields=_links.self.href'
```

Let me know if this works for you and I'll go ahead and close this issue.

~Ryan

**Comment by bohnman** [comment] 2017-05-01 15:16
@frankie-2e  I'm going to assume this is fixed.  If you are still having trouble, please re-open this issue.

**Closed by bohnman** 2017-05-01 15:16 UTC

**Comment by frankie-2e** [comment] 2017-05-02 13:32
Hi Ryan,

Thanks a million for the quick action and fix! 

I wasn't checking the status over the weekend, but can now confirm all of the problems I described in this issue are now fixed.

Best regards,
Frankie

**Comment by bohnman** [comment] 2017-05-02 15:21
@frankie-2e  excellent!  Happy Squiggling!
